##### Write Python program to create two matrices (read values from user) and find the following
1. Dot Product
2. Transpose
3. Trace
4. Rank
5. Determinant
6. Inverse
7. Eigen values and eigen vectors

In [9]:
import numpy as np
n=int(input("Enter the size of the matrix:"))
matrix1 =[]
matrix2 =[]


print("Enter the elements of first matrix row wise") # Reading first matrix
for i in range(n):
    a=[]
    for j in range(n):
        a.append(int(input()))
    matrix1.append(a)
    
    
print("Enter the elements of second matrix row wise")  # Reading second matrix
for i in range(n):
    a=[]
    for j in range(n):
        a.append(int(input()))
    matrix2.append(a)
    
print("=========================================")    
print("First matrix is:")
print(np.matrix(matrix1))  #print the first matrix
print("Second matrix is:")
print(np.matrix(matrix2))  #print the second matrix

print("=========================================")
print("Dot product of both the matrix is:")
print(np.dot(matrix1,matrix2))
print("=========================================")
print("Transpose of first matrix:")
print(np.transpose(matrix1))
print("Transpose of second matrix:")
print(np.transpose(matrix2))
print("=========================================")
print("Trace of first matrix:")
print(np.trace(matrix1))
print("Trace of second matrix:")
print(np.trace(matrix2))
print("=========================================")
print("Rank of first matrix:")
print(np.linalg.matrix_rank(matrix1))
print("Rank of second matrix:")
print(np.linalg.matrix_rank(matrix2))
print("=========================================")

print("Determinant of First matrix")
print(numpy.linalg.det(matrix1))

Enter the size of the matrix:2
Enter the elements of first matrix row wise
1
2
3
4
Enter the elements of second matrix row wise
5
6
7
8
First matrix is:
[[1 2]
 [3 4]]
Second matrix is:
[[5 6]
 [7 8]]
Dot product of both the matrix is:
[[19 22]
 [43 50]]
Transpose of first matrix:
[[1 3]
 [2 4]]
Transpose of second matrix:
[[5 7]
 [6 8]]
Trace of first matrix:
5
Trace of second matrix:
13
Rank of first matrix:
2
Rank of second matrix:
2
