##### Write Python program to create two matrices (read values from user) and find the following
1. Dot Product
2. Transpose
3. Trace
4. Rank
5. Determinant
6. Inverse
7. Eigen values and eigen vectors

In [2]:
import numpy as np
n=int(input("Enter the size of the matrix:"))
matrix1 =[]
matrix2 =[]


print("Enter the elements of first matrix row wise") # Reading first matrix
for i in range(n):
    a=[]
    for j in range(n):
        a.append(int(input()))
    matrix1.append(a)
    
    
print("Enter the elements of second matrix row wise")  # Reading second matrix
for i in range(n):
    a=[]
    for j in range(n):
        a.append(int(input()))
    matrix2.append(a)
    
print("=========================================")    
print("First matrix is:")
print(np.matrix(matrix1))  #print the first matrix
print("Second matrix is:")
print(np.matrix(matrix2))  #print the second matrix

print("=========================================")
print("Dot product of both the matrix is:")
print(np.dot(matrix1,matrix2))
print("=========================================")
print("Transpose of first matrix:")
print(np.transpose(matrix1))
print("Transpose of second matrix:")
print(np.transpose(matrix2))
print("=========================================")
print("Trace of first matrix:")
print(np.trace(matrix1))
print("Trace of second matrix:")
print(np.trace(matrix2))
print("=========================================")
print("Rank of first matrix:")
print(np.linalg.matrix_rank(matrix1))
print("Rank of second matrix:")
print(np.linalg.matrix_rank(matrix2))
print("=========================================")

print("Determinant of First matrix")
print(np.linalg.det(matrix1))

print("Determinant of Second matrix")
print(np.linalg.det(matrix2))

print("=========================================")
print("Inverse of First matrix")
print(np.linalg.inv(matrix1))

print("Inverse of Second matrix")
print(np.linalg.inv(matrix2))

print("=========================================")
print("Eigen Values and Eigen vectors of matrix 1")
w1,v1=np.linalg.eig(matrix1)
print("Eigen values:",w1)
print("Eigen vectors",v1)


print("Eigen Values and Eigen vectors of matrix 2")
w2,v2=np.linalg.eig(matrix2)
print("Eigen values:",w2)
print("Eigen vectors",v2)



Enter the size of the matrix:2
Enter the elements of first matrix row wise
1
5
9
7
Enter the elements of second matrix row wise
5
3
6
8
First matrix is:
[[1 5]
 [9 7]]
Second matrix is:
[[5 3]
 [6 8]]
Dot product of both the matrix is:
[[35 43]
 [87 83]]
Transpose of first matrix:
[[1 9]
 [5 7]]
Transpose of second matrix:
[[5 6]
 [3 8]]
Trace of first matrix:
8
Trace of second matrix:
13
Rank of first matrix:
2
Rank of second matrix:
2
Determinant of First matrix
-37.99999999999999
Determinant of Second matrix
22.000000000000004
Inverse of First matrix
[[-0.18421053  0.13157895]
 [ 0.23684211 -0.02631579]]
Inverse of Second matrix
[[ 0.36363636 -0.13636364]
 [-0.27272727  0.22727273]]
Eigen Values and Eigen vectors of matrix 1
Eigen values: [-3.34846923 11.34846923]
Eigen vectors [[-0.75455746 -0.43504451]
 [ 0.65623398 -0.90040895]]
Eigen Values and Eigen vectors of matrix 2
Eigen values: [ 2. 11.]
Eigen vectors [[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]
