In [1]:
#Write a NumPy program to create an element-wise comparison(greater,greater_equal,less and less_equal) 
#of two given arrays
import numpy as np
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


In [4]:
#Write a NumPy program to create an array of all the even integers from 30 to 70
import numpy as np
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70 are:")
print (array)


Array of all the even integers from 30 to 70 are:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [8]:
#Write a NumPy program to create a 3X3 identity matrix
import numpy as np
array_matrix=np.identity(3)
print("3X3 identity matrix is:")
print(array_matrix)

3X3 identity matrix is:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
